name: Deploy ci-cd-project to CloudHub 2.0

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Publish to Anypoint Exchange
        run: |
          mvn deploy -s settings.xml \
            -DconnectedAppClientId=ca438b3a5de54581bf83c7b756b46579 \
            -DconnectedAppClientSecret=e06BBD80b6564533B8d89b221df860b5\
            -DbusinessGroupId=70de3286-bd1a-4778-b69f-4d3050e04f74

      - name: Deploy to CloudHub 2.0
        run: |
          mvn deploy -DmuleDeploy -s settings.xml \
            DconnectedAppClientId=ca438b3a5de54581bf83c7b756b46579 \
            -DconnectedAppClientSecret=e06BBD80b6564533B8d89b221df860b5\
            -DappName=test-sap-poc123\
            -Denv=Sandbox\
             -DbusinessGroupId=70de3286-bd1a-4778-b69f-4d3050e04f74\
            -Dtarget=Cloudhub-US-East-1
